### PR TITLE
Fix for missing assets in 0.2.5

### PR DESCRIPTION
**Pull request by publicmayhem**
This fixes the missing assets reported by @tuhlmann. I tidied up too much code when I made the previous pull request.

Thx for bearing with me.

### CODE REVIEW

**Comment by yogthos** [comment]
perfect

**Comment by publicmayhem** [comment]
Wow, your quick!!

**Comment by yogthos** [comment]
I try :)

**Comment by yogthos** [comment]
@publicmayhem looks like we're not out of the woods yet on this one https://github.com/yogthos/lein-asset-minifier/issues/8

**Pull request merged**
